In [1]:
import numpy as np
import ot

In [2]:
a = np.array([0.2, 0.5, 0.3])
b = np.array([0.3, 0.4, 0.3])
M = np.array([[0.1, 0.2, 0.3],
              [0.4, 0.5, 0.6],
              [0.7, 0.8, 0.9]])
reg_param = 0.01

In [14]:
def sinkhorn_entropy_regularized_with_distance(a, b, M, reg_param, max_iters=100):
    """
    Sinkhorn算法解决带有熵正则项的最优传输问题，并计算Sinkhorn距离
    :param a: 第一个非负向量
    :param b: 第二个非负向量
    :param M: 距离矩阵
    :param reg_param: 正则项的参数
    :param max_iters: 最大迭代次数
    :return: 最优传输矩阵, Sinkhorn距离
    """
    # 初始化
    n = len(a)
    m = len(b)
    u = np.ones(n)
    v = np.ones(m)

    # 迭代更新
    for _ in range(max_iters):
        K = np.exp(-M / reg_param)  # 使用正则化参数调整距离矩阵
        u = a / (K.dot(v))
        v = b / (K.T.dot(u))

    # 计算最优传输矩阵
    transport_matrix = np.diag(u).dot(K).dot(np.diag(v))

    # 计算Sinkhorn距离
    sinkhorn_distance = np.sum(transport_matrix * M)

    return transport_matrix, sinkhorn_distance

In [15]:
transport_matrix, sinkhorn_distance = sinkhorn_entropy_regularized_with_distance(a, b, M, reg_param)
print("最优传输矩阵：")
print(transport_matrix)
print("Sinkhorn距离：", sinkhorn_distance)

最优传输矩阵：
[[0.06 0.08 0.06]
 [0.15 0.2  0.15]
 [0.09 0.12 0.09]]
Sinkhorn距离： 0.53


In [10]:
# 使用POT库中的sinkhorn2函数求解
optimal_matrix = ot.sinkhorn(a, b, M, reg_param)
sinkhorn_distance = ot.sinkhorn2(a, b, M, reg_param)
print("最优传输矩阵：")
print(transport_matrix)
print("Sinkhorn距离：", sinkhorn_distance)

最优传输矩阵：
[[0.06 0.08 0.06]
 [0.15 0.2  0.15]
 [0.09 0.12 0.09]]
Sinkhorn距离： 0.53
